// Command doccheck checks package documentation, local Markdown links and API freshness.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode"
)

func main() {
	root := flag.String("root", ".", "repository root")
	write := flag.Bool("write-api", false, "regenerate Cordis API reference")
	coverage := flag.String("coverage", "", "require at least 90 percent Cordis statement coverage")
	examples := flag.Bool("examples", false, "run documented Go programs and compare their output")
	flag.Parse()
	var err error
	if *coverage != "" {
		err = checkCoverage(*coverage)
	} else if *examples {
		err = checkExamples(*root)
	} else {
		if *write {
			var api []byte
			api, err = renderAPI(*root)
			if err == nil {
				err = os.WriteFile(filepath.Join(*root, "docs/cordis/api.md"), api, 0644)
			}
		}
		if err == nil {
			err = checkDocs(*root)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Println("documentation gate passed")
}

func sourceFiles(root string) ([]string, error) {
	var paths []string
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() && (d.Name() == ".git" || d.Name() == "bin" || d.Name() == "validation") {
			return filepath.SkipDir
		}
		if !d.IsDir() && strings.HasSuffix(path, ".go") && !strings.HasSuffix(path, "_test.go") {
			paths = append(paths, path)
		}
		return nil
	})
	sort.Strings(paths)
	return paths, err
}

func documented(group *ast.CommentGroup, name string) bool {
	return group != nil && strings.HasPrefix(strings.TrimSpace(group.Text()), name)
}

func checkExports(path string) error {
	f, err := parser.ParseFile(token.NewFileSet(), path, nil, parser.ParseComments)
	if err != nil {
		return err
	}
	var errs []error
	missing := func(name string) {
		errs = append(errs, fmt.Errorf("%s: exported %s needs a comment beginning with its name", path, name))
	}
	for _, decl := range f.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			if d.Name.IsExported() && !documented(d.Doc, d.Name.Name) {
				missing(d.Name.Name)
			}
		case *ast.GenDecl:
			for _, spec := range d.Specs {
				switch s := spec.(type) {
				case *ast.TypeSpec:
					if !s.Name.IsExported() {
						continue
					}
					doc := s.Doc
					if doc == nil {
						doc = d.Doc
					}
					if !documented(doc, s.Name.Name) {
						missing(s.Name.Name)
					}
					if st, ok := s.Type.(*ast.StructType); ok {
						for _, field := range st.Fields.List {
							for _, name := range field.Names {
								if name.IsExported() && !documented(field.Doc, name.Name) {
									missing(s.Name.Name + "." + name.Name)
								}
							}
						}
					}
				case *ast.ValueSpec:
					for _, name := range s.Names {
						if name.IsExported() {
							doc := s.Doc
							if doc == nil {
								doc = d.Doc
							}
							if !documented(doc, name.Name) {
								missing(name.Name)
							}
						}
					}
				}
			}
		}
	}
	return errors.Join(errs...)
}

func renderAPI(root string) ([]byte, error) {
	paths, err := filepath.Glob(filepath.Join(root, "cordis", "*.go"))
	if err != nil {
		return nil, err
	}
	var out bytes.Buffer
	out.WriteString("# Cordis API\n\n<!-- Generated by go run ./scripts/doccheck -write-api; edit Go comments. -->\n\n本页从 Go 源码和公开注释生成。行为说明见 [生命周期](lifecycle.md)、[服务与作用域](services.md) 和 [事件](events.md)。\n")
	for _, path := range paths {
		if strings.HasSuffix(path, "_test.go") {
			continue
		}
		fset := token.NewFileSet()
		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return nil, err
		}
		for _, decl := range file.Decls {
			var name, doc string
			var node ast.Node
			switch d := decl.(type) {
			case *ast.FuncDecl:
				if !d.Name.IsExported() {
					continue
				}
				name = d.Name.Name
				if d.Recv != nil {
					var recv bytes.Buffer
					_ = format.Node(&recv, fset, d.Recv.List[0].Type)
					name = recv.String() + "." + name
				}
				if d.Doc != nil {
					doc = d.Doc.Text()
				}
				copy := *d
				copy.Body = nil
				copy.Doc = nil
				node = &copy
			case *ast.GenDecl:
				if d.Tok != token.TYPE {
					continue
				}
				for _, spec := range d.Specs {
					if s, ok := spec.(*ast.TypeSpec); ok && s.Name.IsExported() {
						name = s.Name.Name
						if s.Doc != nil {
							doc = s.Doc.Text()
						} else if d.Doc != nil {
							doc = d.Doc.Text()
						}
						node = &ast.GenDecl{Tok: token.TYPE, Specs: []ast.Spec{s}}
					}
				}
			}
			if node == nil {
				continue
			}
			fmt.Fprintf(&out, "\n## %s\n\n%s\n```go\n", name, strings.TrimSpace(doc))
			if err := format.Node(&out, fset, node); err != nil {
				return nil, err
			}
			out.WriteString("\n```\n")
		}
	}
	// Constants and sentinel errors retain their own complete comments in source.
	out.WriteString("\n## 状态与错误\n\n生命周期状态：`Pending`、`Loading`、`Active`、`Failed`、`Unloading`、`Disposed`。可用 `errors.Is` 判断 `ErrInactive`、`ErrDuplicateService`、`ErrServiceNotFound`、`ErrServiceType`。定义见 [fiber.go](../../cordis/fiber.go) 和 [plugin.go](../../cordis/plugin.go)。\n")
	return out.Bytes(), nil
}

func checkDocs(root string) error {
	paths, err := sourceFiles(root)
	if err != nil {
		return err
	}
	var errs []error
	packages := map[string]bool{}
	for _, path := range paths {
		if err := checkExports(path); err != nil {
			errs = append(errs, err)
		}
		packages[filepath.Dir(path)] = true
	}
	for dir := range packages {
		readme := filepath.Join(dir, "README.md")
		_, err := os.Stat(readme)
		if err != nil {
			errs = append(errs, fmt.Errorf("package %s needs README.md", dir))
			continue
		}
		// One package comment must exist in each package, including commands.
		documentedPackage := false
		for _, path := range paths {
			if filepath.Dir(path) == dir {
				f, _ := parser.ParseFile(token.NewFileSet(), path, nil, parser.ParseComments)
				if f != nil && f.Doc != nil {
					documentedPackage = true
				}
			}
		}
		if !documentedPackage {
			errs = append(errs, fmt.Errorf("package %s needs a package comment", dir))
		}
	}
	err = filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() && (d.Name() == ".git" || d.Name() == "bin" || d.Name() == "validation") {
			return filepath.SkipDir
		}
		if !d.IsDir() && strings.HasSuffix(path, ".md") {
			if d.Name() == "README.md" {
				if err := checkREADME(root, path); err != nil {
					errs = append(errs, err)
				}
			}
			if err := checkCodeBlocks(root, path, false); err != nil {
				errs = append(errs, err)
			}
			if err := checkLinks(root, path); err != nil {
				errs = append(errs, err)
			}
		}
		return nil
	})
	if err != nil {
		errs = append(errs, err)
	}
	want, err := renderAPI(root)
	if err != nil {
		errs = append(errs, err)
	} else {
		got, err := os.ReadFile(filepath.Join(root, "docs/cordis/api.md"))
		if err != nil || !bytes.Equal(want, got) {
			errs = append(errs, errors.New("Cordis API stale: run go run ./scripts/doccheck -write-api"))
		}
	}
	return errors.Join(errs...)
}

var markdownLink = regexp.MustCompile(`\[[^\]]*\]\(([^)]+)\)`)
var inlineCode = regexp.MustCompile("`[^`]*`")

func checkLinks(root, path string) error {
	body, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	var errs []error
	for _, match := range markdownLink.FindAllStringSubmatch(inlineCode.ReplaceAllString(stripFences(string(body)), ""), -1) {
		target := strings.Trim(match[1], "<>")
		if strings.Contains(target, "://") || strings.HasPrefix(target, "mailto:") {
			continue
		}
		parts := strings.SplitN(target, "#", 2)
		dest := path
		if parts[0] != "" {
			dest = filepath.Clean(filepath.Join(filepath.Dir(path), filepath.FromSlash(parts[0])))
		}
		rel, err := filepath.Rel(root, dest)
		if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
			errs = append(errs, fmt.Errorf("%s: link escapes repo: %s", path, target))
			continue
		}
		info, err := os.Stat(dest)
		if err != nil {
			errs = append(errs, fmt.Errorf("%s: broken link %s", path, target))
			continue
		}
		if len(parts) == 2 && parts[1] != "" && strings.HasSuffix(dest, ".md") && !info.IsDir() {
			text, _ := os.ReadFile(dest)
			found := false
			for _, line := range strings.Split(stripFences(string(text)), "\n") {
				if strings.HasPrefix(line, "#") {
					title := strings.TrimSpace(strings.TrimLeft(line, "#"))
					if slug(title) == parts[1] {
						found = true
					}
				}
			}
			if !found {
				errs = append(errs, fmt.Errorf("%s: missing fragment %s", path, target))
			}
		}
	}
	return errors.Join(errs...)
}

func stripFences(body string) string {
	blocks, _ := codeBlocks(body)
	var out strings.Builder
	blockIndex := 0
	for index, line := range strings.Split(body, "\n") {
		for blockIndex < len(blocks) && index+1 > blocks[blockIndex].end {
			blockIndex++
		}
		if blockIndex == len(blocks) || index+1 < blocks[blockIndex].line {
			out.WriteString(line)
			out.WriteByte('\n')
		}
	}
	return out.String()
}

func slug(title string) string {
	var out strings.Builder
	for _, r := range strings.ToLower(title) {
		if unicode.IsLetter(r) || unicode.IsNumber(r) || r == '-' || r == '_' {
			out.WriteRune(r)
		} else if r == ' ' {
			out.WriteByte('-')
		}
	}
	return out.String()
}

func checkCoverage(path string) error {
	body, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	var total, covered int
	for _, line := range strings.Split(string(body), "\n") {
		if !strings.HasPrefix(line, "github.com/gosomea/deepseek-harness-go/cordis/") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) != 3 {
			return fmt.Errorf("invalid coverage line: %s", line)
		}
		var statements, count int
		if _, err := fmt.Sscanf(fields[1]+" "+fields[2], "%d %d", &statements, &count); err != nil {
			return err
		}
		total += statements
		if count > 0 {
			covered += statements
		}
	}
	if total == 0 || covered*100 < total*90 {
		return fmt.Errorf("Cordis coverage below 90%%: %d/%d statements", covered, total)
	}
	fmt.Printf("Cordis coverage: %.1f%%\n", 100*float64(covered)/float64(total))
	return nil
}
